### ISSUE TITLE
How could I test this project ?

### ISSUE THREAD

**Issue by keyolk** [kost/dockscan#2]
Hello
I'm tyring to use this project for my local laptop

I use archlinux based distro

here is my docker info

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.1-1-ARCH
Operating System: Apricity OS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.61 GiB
Name: keyolk-book
ID: AKMT:LO4B:TAXU:M6K3:RYEQ:GE5B:GLZ6:ISBQ:WBN7:FYKF:CMN6:TN2W
Docker Root Dir: /home/keyolk/mount/flash/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

when I try below

```
./dockscan.rb -r html -o myreport -v unix:///var/run/docker.sock
```

I got below message

```
/home/keyolk/workspace/build/git/dockscan/scan/manage-scan.rb:35:in `scan': undefined method `url=' for Docker:Module (NoMethodError)
        from ./dockscan.rb:101:in `block in <main>'
        from ./dockscan.rb:100:in `each'
        from ./dockscan.rb:100:in `<main>'
```

How can I fix this ?

**Comment by kost** [comment]
Hello!

Thanks for trying out dockscan. Are you using ruby version 1.9.x? If yes, it does not work (Ruby 1.9.x versions are deprecated!). 

If you have Ruby version 2 or above, you can just say following:
`sudo gem install dockscan`

and then scan as usual

 `dockscan -r html -o myreport -v unix:///var/run/docker.sock`

Let me know if it works for you!

**Comment by keyolk** [comment]
Thanks to reply!
it works well
